version: '3.8'

services:
  wordpress:
    image: wordpress:6.4-php8.2-fpm
    container_name: ecolitio_wp
    restart: unless-stopped
    environment:
      # Conexión a staging database
      WORDPRESS_DB_HOST: ${STAGING_DB_HOST}
      WORDPRESS_DB_NAME: ${STAGING_DB_NAME}
      WORDPRESS_DB_USER: ${STAGING_DB_USER}
      WORDPRESS_DB_PASSWORD: ${STAGING_DB_PASSWORD}
      
      # Configuración de desarrollo
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('SCRIPT_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('FS_METHOD', 'direct');
    volumes:
      # Mapeo del tema en desarrollo
      - ./themes/ecolitio-theme:/var/www/html/wp-content/themes/ecolitio-theme
      # Mapeo de plugins personalizados
      - ./plugins:/var/www/html/wp-content/plugins
      # Mapeo de uploads (opcional, para archivos locales)
      - ./uploads:/var/www/html/wp-content/uploads
      # Log files
      - ./logs/wordpress.log:/var/log/wordpress.log
    depends_on:
      - nginx
    networks:
      - ecolitio_network

  nginx:
    image: nginx:alpine
    container_name: ecolitio_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
      # Mapeo para servir archivos estáticos
      - ./themes/ecolitio-theme:/var/www/html/wp-content/themes/ecolitio-theme
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - wordpress
    networks:
      - ecolitio_network

  # WP-CLI para comandos de WordPress
  wp-cli:
    image: wordpress:cli-php8.2
    container_name: ecolitio_wp_cli
    environment:
      WORDPRESS_DB_HOST: ${STAGING_DB_HOST}
      WORDPRESS_DB_NAME: ${STAGING_DB_NAME}
      WORDPRESS_DB_USER: ${STAGING_DB_USER}
      WORDPRESS_DB_PASSWORD: ${STAGING_DB_PASSWORD}
    volumes:
      - ./themes/ecolitio-theme:/var/www/html/wp-content/themes/ecolitio-theme
      - ./plugins:/var/www/html/wp-content/plugins
    networks:
      - ecolitio_network
    profiles:
      - cli

  # phpMyAdmin para gestionar la DB (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecolitio_pma
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${STAGING_DB_HOST}
      PMA_PORT: 3306
      PMA_USER: ${STAGING_DB_USER}
      PMA_PASSWORD: ${STAGING_DB_PASSWORD}
    profiles:
      - tools
    networks:
      - ecolitio_network

networks:
  ecolitio_network:
    driver: bridge

volumes:
  wp_data: